// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NEXUS.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NEXUS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NEXUS.Data.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("District")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("GPSCoordinates")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SuspectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SuspectId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DirectCommanderId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleTitle")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SuspectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DirectCommanderId");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("SuspectId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.BayahDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RecruiterName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("SuspectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextOfPledge")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SuspectId");

                    b.ToTable("BayahDetails");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaseFileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InvestigatingOfficer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("OpenDate")
                        .HasColumnType("date");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SuspectsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CaseFileNumber");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.CaseSuspect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccusationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ConfessionDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<int>("LegalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("SuspectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("SuspectId");

                    b.ToTable("CaseSuspects");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SuspectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SuspectId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.EntityWatchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlertLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("EntityWatchlists");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.EvidenceAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("HashChecksum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SuspectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("SuspectId");

                    b.ToTable("EvidenceAttachments");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.InterrogationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InterrogatorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InvestigatorNotes")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRatifiedByJudge")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SuspectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("SuspectId");

                    b.ToTable("InterrogationSessions");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.LifeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CivilianJobs")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<string>("RadicalizationStory")
                        .HasColumnType("text");

                    b.Property<string>("SchoolsAttended")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SuspectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SuspectId");

                    b.ToTable("LifeHistories");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Associates")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<string>("RoleInOp")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SuspectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SuspectId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.OrgUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentUnitId");

                    b.ToTable("OrgUnits");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.RelatedPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStatus")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("FivthName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("FourthName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Relationship")
                        .HasColumnType("integer");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("SpouseName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SuspectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Tribe")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("SuspectId");

                    b.ToTable("RelatedPeople");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Suspect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeNum")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("FivthName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("FourthName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kunya")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LegalArticle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MaritalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("MotherName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Tribe")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("WivesCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodeNum");

                    b.ToTable("Suspects");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.SystemAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SystemAlerts");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.SystemAuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OldValues")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RecordId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LogId");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.TrainingCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Classmates")
                        .HasColumnType("text");

                    b.Property<int>("CourseType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SuspectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrainerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SuspectId");

                    b.ToTable("TrainingCourses");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Address", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany("Addresses")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Assignment", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Suspect", "DirectCommander")
                        .WithMany()
                        .HasForeignKey("DirectCommanderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NEXUS.Data.Entities.OrgUnit", "OrgUnit")
                        .WithMany("Assignments")
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany("OrganizationalAssignments")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DirectCommander");

                    b.Navigation("OrgUnit");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.BayahDetail", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany("BayahDetails")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.CaseSuspect", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Case", "Case")
                        .WithMany("SuspectsInvolved")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany("CaseInvolvements")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Contact", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany("Contacts")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.EvidenceAttachment", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Case", "Case")
                        .WithMany("Attachments")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany()
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.InterrogationSession", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany()
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.LifeHistory", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany("LifeHistories")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Operation", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany("Operations")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.OrgUnit", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.OrgUnit", "ParentUnit")
                        .WithMany("SubUnits")
                        .HasForeignKey("ParentUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentUnit");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.RelatedPerson", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany("RelativesAndAssociates")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.TrainingCourse", b =>
                {
                    b.HasOne("NEXUS.Data.Entities.Suspect", "Suspect")
                        .WithMany("TrainingCourses")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Case", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("SuspectsInvolved");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.OrgUnit", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("SubUnits");
                });

            modelBuilder.Entity("NEXUS.Data.Entities.Suspect", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BayahDetails");

                    b.Navigation("CaseInvolvements");

                    b.Navigation("Contacts");

                    b.Navigation("LifeHistories");

                    b.Navigation("Operations");

                    b.Navigation("OrganizationalAssignments");

                    b.Navigation("RelativesAndAssociates");

                    b.Navigation("TrainingCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
